services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    working_dir: /app
    command: bun dev --host
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    working_dir: /app
    command: poetry run uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./backend:/app